### ISSUE TITLE
Error: Cannot find module 'dirutils'

### ISSUE THREAD

**Issue by bbigras** [acheronfail/xi-electron#10]
13cab845c7a8dccf596859f86cd64da8a7e7d9c4
Arch Linux 64-bit

```
% yarn make                                                                                                                            :(
yarn run v1.3.2
$ electron-forge make
✔ Checking your system
✔ Resolving Forge Config
We need to package your application before we can make it
✔ Preparing to Package Application for arch: x64
✔ Compiling Application

An unhandled rejection has occurred inside Forge:
Command failed: yarn install --production --no-bin-links --no-lockfile
warning electron-forge > s3 > graceful-fs@3.0.11: please upgrade to graceful-fs 4 for compatibility with current and future versions of Node.js
warning electron-forge > zip-folder > archiver > glob > minimatch@0.3.0: Please update to minimatch 3.0.2 or higher to avoid a RegExp DoS issue
warning electron-forge > electron-windows-store > flatten-packages > wrench@1.5.9: wrench.js is deprecated! You should check out fs-extra (https://github.com/jprichardson/node-fs-extra) for any operations you were using wrench for. Thanks for all the usage over the years.
warning electron-forge > nugget > progress-stream > through2 > xtend > object-keys@0.4.0: 
warning electron-prebuilt-compile > electron-compilers > coffee-script@1.12.7: CoffeeScript on NPM has moved to "coffeescript" (no hyphen)
warning electron-prebuilt-compile > electron-compilers > cson > coffee-script@1.12.7: CoffeeScript on NPM has moved to "coffeescript" (no hyphen)
warning electron-prebuilt-compile > electron-compilers > jade@1.11.0: Jade has been renamed to pug, please install the latest version of pug instead of jade
warning electron-prebuilt-compile > electron-compilers > jade > transformers@2.1.0: Deprecated, use jstransformer
module.js:557
    throw err;
    ^

Error: Cannot find module 'dirutils'
    at Function.Module._resolveFilename (module.js:555:15)
    at Function.Module._load (module.js:482:25)
    at Module.require (module.js:604:17)
    at require (internal/module.js:11:18)
    at Object.<anonymous> (/tmp/electron-packager/linux-x64/xi-electron-ts-linux-x64/resources/app/scripts/postinstall.js:9:1)
    at Module._compile (module.js:660:30)
    at Object.Module._extensions..js (module.js:671:10)
    at Module.load (module.js:573:32)
    at tryModuleLoad (module.js:513:12)
    at Function.Module._load (module.js:505:3)
error Command failed with exit code 1.

Error: Command failed: yarn install --production --no-bin-links --no-lockfile
warning electron-forge > s3 > graceful-fs@3.0.11: please upgrade to graceful-fs 4 for compatibility with current and future versions of Node.js
warning electron-forge > zip-folder > archiver > glob > minimatch@0.3.0: Please update to minimatch 3.0.2 or higher to avoid a RegExp DoS issue
warning electron-forge > electron-windows-store > flatten-packages > wrench@1.5.9: wrench.js is deprecated! You should check out fs-extra (https://github.com/jprichardson/node-fs-extra) for any operations you were using wrench for. Thanks for all the usage over the years.
warning electron-forge > nugget > progress-stream > through2 > xtend > object-keys@0.4.0: 
warning electron-prebuilt-compile > electron-compilers > coffee-script@1.12.7: CoffeeScript on NPM has moved to "coffeescript" (no hyphen)
warning electron-prebuilt-compile > electron-compilers > cson > coffee-script@1.12.7: CoffeeScript on NPM has moved to "coffeescript" (no hyphen)
warning electron-prebuilt-compile > electron-compilers > jade@1.11.0: Jade has been renamed to pug, please install the latest version of pug instead of jade
warning electron-prebuilt-compile > electron-compilers > jade > transformers@2.1.0: Deprecated, use jstransformer
module.js:557
    throw err;
    ^

Error: Cannot find module 'dirutils'
    at Function.Module._resolveFilename (module.js:555:15)
    at Function.Module._load (module.js:482:25)
    at Module.require (module.js:604:17)
    at require (internal/module.js:11:18)
    at Object.<anonymous> (/tmp/electron-packager/linux-x64/xi-electron-ts-linux-x64/resources/app/scripts/postinstall.js:9:1)
    at Module._compile (module.js:660:30)
    at Object.Module._extensions..js (module.js:671:10)
    at Module.load (module.js:573:32)
    at tryModuleLoad (module.js:513:12)
    at Function.Module._load (module.js:505:3)
error Command failed with exit code 1.

    at ChildProcess.exithandler (child_process.js:272:12)
    at ChildProcess.emit (events.js:160:13)
    at maybeClose (internal/child_process.js:943:16)
    at Socket.stream.socket.on (internal/child_process.js:363:11)
    at Socket.emit (events.js:160:13)
    at Pipe._handle.close [as _onclose] (net.js:559:12)
error Command failed with exit code 1.
info Visit https://yarnpkg.com/en/docs/cli/run for documentation about this command.
yarn make  30,54s user 6,75s system 106% cpu 34,904 total
```

**Comment by jsnanigans** [comment]
Same exact error for me.
here is the npm error log:
```log
0 info it worked if it ends with ok
1 verbose cli [ '/home/x/.nvm/versions/node/v8.9.4/bin/node',
1 verbose cli   '/home/x/.nvm/versions/node/v8.9.4/bin/npm',
1 verbose cli   'run',
1 verbose cli   'make' ]
2 info using npm@5.6.0
3 info using node@v8.9.4
4 verbose run-script [ 'premake', 'make', 'postmake' ]
5 info lifecycle xi-electron-ts@1.0.0~premake: xi-electron-ts@1.0.0
6 info lifecycle xi-electron-ts@1.0.0~make: xi-electron-ts@1.0.0
7 verbose lifecycle xi-electron-ts@1.0.0~make: unsafe-perm in lifecycle true
8 verbose lifecycle xi-electron-ts@1.0.0~make: PATH: /home/x/.nvm/versions/node/v8.9.4/lib/node_modules/npm/node_modules/npm-lifecycle/node-gyp-bin:/home/x/red/side/gh/xi-electron/node_modules/.bin:/home/x/.yarn/bin:/home/x/.nvm/versions/node/v8.9.4/bin:/home/x/.cargo/bin:/home/x/.cargo/bin:/home/x/bin:/home/x/.local/bin:/usr/local/sbin:/usr/local/bin:/usr/sbin:/usr/bin:/sbin:/bin:/usr/gam
es:/usr/local/games:/snap/bin
9 verbose lifecycle xi-electron-ts@1.0.0~make: CWD: /home/x/red/side/gh/xi-electron
10 silly lifecycle xi-electron-ts@1.0.0~make: Args: [ '-c', 'electron-forge make' ]
11 silly lifecycle xi-electron-ts@1.0.0~make: Returned: code: 1  signal: null
12 info lifecycle xi-electron-ts@1.0.0~make: Failed to exec make script
13 verbose stack Error: xi-electron-ts@1.0.0 make: `electron-forge make`
13 verbose stack Exit status 1
13 verbose stack     at EventEmitter.<anonymous> (/home/x/.nvm/versions/node/v8.9.4/lib/node_modules/npm/node_modules/npm-lifecycle/index.js:285:16)
13 verbose stack     at emitTwo (events.js:126:13)
13 verbose stack     at EventEmitter.emit (events.js:214:7)
13 verbose stack     at ChildProcess.<anonymous> (/home/x/.nvm/versions/node/v8.9.4/lib/node_modules/npm/node_modules/npm-lifecycle/lib/spawn.js:55:14)
13 verbose stack     at emitTwo (events.js:126:13)
13 verbose stack     at ChildProcess.emit (events.js:214:7)
13 verbose stack     at maybeClose (internal/child_process.js:925:16)
13 verbose stack     at Process.ChildProcess._handle.onexit (internal/child_process.js:209:5)
14 verbose pkgid xi-electron-ts@1.0.0
15 verbose cwd /home/x/red/side/gh/xi-electron
16 verbose Linux 4.13.0-32-generic
17 verbose argv "/home/x/.nvm/versions/node/v8.9.4/bin/node" "/home/x/.nvm/versions/node/v8.9.4/bin/npm" "run" "make"
18 verbose node v8.9.4
19 verbose npm  v5.6.0
20 error code ELIFECYCLE
21 error errno 1
22 error xi-electron-ts@1.0.0 make: `electron-forge make`
22 error Exit status 1
23 error Failed at the xi-electron-ts@1.0.0 make script.
23 error This is probably not a problem with npm. There is likely additional logging output above.
24 verbose exit [ 1, true ]
```

**Comment by acheronfail** [comment]
Hmm I thought that the `dirutils` package may give us some issues... I’ll re-write the install script without it sometime this week.

**Comment by acheronfail** [comment]
@bbigras @jsnanigans Turned out to be a lot simpler than I thought.

Update to the latest, and then make sure you run:

```sh
yarn # has to be run at least once to install dependencies
yarn make
```

Let me know if you encounter any issues 😄

**Comment by jsnanigans** [comment]
Nice it worked after I updated yarn to 1.3.2 and node to 8.9.4
Thanks :+1:
