### ISSUE TITLE
NMAKE : Fatal Error U1077

### ISSUE THREAD

**Issue by xNul** [acheronfail/xi-electron#14]
Tried to compile on Windows again and this error shows up after using the first yarn command.  Is there a problem with my version of Visual Studio?

```
C:\Users\l\xi-electron>yarn
yarn install v1.3.2
[1/4] Resolving packages...
success Already up-to-date.
$ node scripts/postinstall.js
Starting build of xi-core...
fatal: Not a git repository (or any of the parent directories): .git
    Finished release [optimized] target(s) in 0.0 secs
Build complete!
xi-core was built and placed in: "C:\Users\l\xi-electron\src\xi\xi-core.exe".
Building plugins...
   Compiling onig_sys v67.1.0
error: failed to run custom build command for `onig_sys v67.1.0`
process didn't exit successfully: `C:\Users\l\xi-electron\xi-editor\rust\syntect-plugin\target\release\build\onig_sys-4fcc09625b576858\build-script-build` (exit code: 101)
--- stderr

Microsoft (R) Program Maintenance Utility Version 14.00.24210.0
Copyright (C) Microsoft Corporation.  All rights reserved.

NMAKE : fatal error U1077: '"C:\Program Files (x86)\Microsoft Visual Studio 14.0\VC\bin\cl.EXE"' : return code '0x2'
Stop.
thread 'main' panicked at 'called `Result::unwrap()` on an `Err` value: Error { repr: Custom(Custom { kind: Other, error: StringError("command [\"cmd\", \"/c\", \"C:\\\\Users\\\\l\\\\.cargo\\\\registry\\\\src\\\\github.com-1ecc6299db9ec823\\\\onig_sys-67.1.0\\\\oniguruma\\\\make_win64.bat\"] exited with code 2") }) }', src\libcore\result.rs:906:4
note: Run with `RUST_BACKTRACE=1` for a backtrace.

C:\Users\l\xi-electron\scripts\postinstall.js:54
  throw res.error || new Error('Could not build syntect-plugin!');
  ^

Error: Could not build syntect-plugin!
    at Object.<anonymous> (C:\Users\l\xi-electron\scripts\postinstall.js:54:22)
    at Module._compile (module.js:570:32)
    at Object.Module._extensions..js (module.js:579:10)
    at Module.load (module.js:487:32)
    at tryModuleLoad (module.js:446:12)
    at Function.Module._load (module.js:438:3)
    at Module.runMain (module.js:604:10)
    at run (bootstrap_node.js:389:7)
    at startup (bootstrap_node.js:149:9)
    at bootstrap_node.js:502:3
error Command failed with exit code 1.
info Visit https://yarnpkg.com/en/docs/cli/install for documentation about this command.
```

I then tried to build onig_sys directly and found some more details on the error:

```
C:\Users\l\.cargo\registry\src\github.com-1ecc6299db9ec823\onig_sys-67.1.0\oniguruma>make_win64.bat

C:\Users\l\.cargo\registry\src\github.com-1ecc6299db9ec823\onig_sys-67.1.0\oniguruma>SET ONIG_DIR=C:\Users\l\.cargo\registry\src\github.com-1ecc6299db9ec823\onig_sys-67.1.0\oniguruma\\src

C:\Users\l\.cargo\registry\src\github.com-1ecc6299db9ec823\onig_sys-67.1.0\oniguruma>set THIS_DIR=C:\Users\l\.cargo\registry\src\github.com-1ecc6299db9ec823\onig_sys-67.1.0\oniguruma\

C:\Users\l\.cargo\registry\src\github.com-1ecc6299db9ec823\onig_sys-67.1.0\oniguruma>set BUILD_DIR=C:\Users\l\.cargo\registry\src\github.com-1ecc6299db9ec823\onig_sys-67.1.0\oniguruma

C:\Users\l\.cargo\registry\src\github.com-1ecc6299db9ec823\onig_sys-67.1.0\oniguruma>copy C:\Users\l\.cargo\registry\src\github.com-1ecc6299db9ec823\onig_sys-67.1.0\oniguruma\\src\config.h.win64 C:\Users\l\.cargo\registry\src\github.com-1ecc6299db9ec823\onig_sys-67.1.0\oniguruma\config.h
        1 file(s) copied.

C:\Users\l\.cargo\registry\src\github.com-1ecc6299db9ec823\onig_sys-67.1.0\oniguruma>nmake -f C:\Users\l\.cargo\registry\src\github.com-1ecc6299db9ec823\onig_sys-67.1.0\oniguruma\\src\Makefile.windows

Microsoft (R) Program Maintenance Utility Version 14.00.24210.0
Copyright (C) Microsoft Corporation.  All rights reserved.

        cl -O2 -nologo /W3  -DHAVE_CONFIG_H -DNOT_RUBY -DONIGURUMA_EXPORT /I. /I.. /FoC:\Users\l\.cargo\registry\src\github.com-1ecc6299db9ec823\onig_sys-67.1.0\oniguruma/reggnu.obj /c C:\Users\l\.cargo\registry\src\github.com-1ecc6299db9ec823\onig_sys-67.1.0\oniguruma\\src\reggnu.c
reggnu.c
c:\users\l\.cargo\registry\src\github.com-1ecc6299db9ec823\onig_sys-67.1.0\oniguruma\src\regint.h(149): fatal error C1083: Cannot open include file: 'stddef.h': No such file or directory
NMAKE : fatal error U1077: '"C:\Program Files (x86)\Microsoft Visual Studio 14.0\VC\bin\cl.EXE"' : return code '0x2'
Stop.
```

It seems like the compiler can't find a required file called stddef.h

**Comment by acheronfail** [comment]
For now, issues encountered when building `xi-core` should be directed upstream to [`xi-editor` itself](https://github.com/google/xi-editor). 

For setup on Windows platforms, we'll track that issue in #13.

**Comment by xNul** [comment]
Ok, I've closed this issue in that case.  I'll try to sort it out with them.

**Comment by acheronfail** [comment]
That would be awesome - thanks!
If you do find a solution please let me know 😄
