### ISSUE TITLE
Error: ENOENT: no such file or directory, uv_chdir

### ISSUE THREAD

**Issue by xNul** [acheronfail/xi-electron#9]
Tried to compile on Windows and this error shows up after using the first yarn command or the npm install command.  I tried installing and reinstalling the react-native module, updating npm, and other solutions I found through Google to no avail.

```
C:\Users\h\xi-electron>yarn
yarn install v1.3.2
[1/4] Resolving packages...
warning react-native > connect@2.30.2: connect 2.x series is deprecated
warning react-native > fbjs-scripts > gulp-util@3.0.8: gulp-util is deprecated - replace it, following the guidelines at https://medium.com/gulpjs/gulp-util-ca3b1f9f9ac5
[2/4] Fetching packages...
info fsevents@1.1.3: The platform "win32" is incompatible with this module.
info "fsevents@1.1.3" is an optional dependency and failed compatibility check. Excluding it from installation.
info electron-installer-debian@0.7.1: The platform "win32" is incompatible with this module.
info "electron-installer-debian@0.7.1" is an optional dependency and failed compatibility check. Excluding it from installation.
info electron-installer-flatpak@0.8.0: The platform "win32" is incompatible with this module.
info "electron-installer-flatpak@0.8.0" is an optional dependency and failed compatibility check. Excluding it from installation.
info electron-installer-redhat@0.5.0: The platform "win32" is incompatible with this module.
info "electron-installer-redhat@0.5.0" is an optional dependency and failed compatibility check. Excluding it from installation.
info appdmg@0.4.5: The platform "win32" is incompatible with this module.
info "appdmg@0.4.5" is an optional dependency and failed compatibility check. Excluding it from installation.
info fs-xattr@0.1.17: The platform "win32" is incompatible with this module.
info "fs-xattr@0.1.17" is an optional dependency and failed compatibility check. Excluding it from installation.
info macos-alias@0.2.11: The platform "win32" is incompatible with this module.
info "macos-alias@0.2.11" is an optional dependency and failed compatibility check. Excluding it from installation.
[3/4] Linking dependencies...
[4/4] Building fresh packages...
success Saved lockfile.
$ node scripts/postinstall.js
Starting build of xi-core...
C:\Users\h\xi-electron\node_modules\graceful-fs\polyfills.js:21
  chdir.call(process, d)
        ^

Error: ENOENT: no such file or directory, uv_chdir
    at Error (native)
    at process.chdir (C:\Users\h\xi-electron\node_modules\graceful-fs\polyfills.js:21:9)
    at process.value (C:\Users\h\xi-electron\node_modules\dirutils\lib\dirutils.js:30:17)
    at Object.<anonymous> (C:\Users\h\xi-electron\scripts\postinstall.js:20:9)
    at Module._compile (module.js:570:32)
    at Object.Module._extensions..js (module.js:579:10)
    at Module.load (module.js:487:32)
    at tryModuleLoad (module.js:446:12)
    at Function.Module._load (module.js:438:3)
    at Module.runMain (module.js:604:10)
error Command failed with exit code 1.
info Visit https://yarnpkg.com/en/docs/cli/install for documentation about this command.
```

**Comment by acheronfail** [comment]
I've just removed the `dirutils` dependency (which this is coming from) in 264c8af, so update to the latest and try running `yarn` again 😄 

I think this change has fixed the issue, so I'm closing it. Feel free to let me know if that's not the case!

**Comment by xNul** [comment]
Thanks!  This error does seem to be gone, but a new one has now come up.  I opened a new issue at #14
